import React from 'react';
import { prisma } from '@/lib/db';
import { Mail, ExternalLink, Send, CheckCircle2 } from 'lucide-react';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function FollowUpsPage() {
  const followUps = await prisma.followUp.findMany({
    orderBy: { createdAt: 'desc' },
    include: { lead: true },
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white border border-gray-200 p-6 rounded-xl shadow-card">
        <div>
          <h1 className="text-xl font-bold text-gray-900 tracking-tight flex items-center gap-2">
            <Mail className="w-5 h-5 text-purple-600" /> Automated Follow-up Draft Manager
          </h1>
          <p className="text-xs text-gray-500 mt-1">
            Personalized email responses generated by AI and dispatched via Mailpit SMTP.
          </p>
        </div>

        <a
          href="http://localhost:8025"
          target="_blank"
          rel="noreferrer"
          className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 border border-gray-200 hover:border-blue-600 text-gray-700 text-xs font-mono rounded-lg transition flex items-center gap-1.5"
        >
          Open Mailpit Inbox (8025) <ExternalLink className="w-3.5 h-3.5 text-blue-600" />
        </a>
      </div>

      <div className="bg-white border border-gray-200 rounded-xl p-6 space-y-4 card-hover">
        {followUps.length === 0 ? (
          <div className="text-center p-8 text-gray-500 text-xs">
            No follow-up drafts generated yet. Submit a qualified lead to trigger automated generation.
          </div>
        ) : (
          <div className="space-y-4">
            {followUps.map((draft) => (
              <div
                key={draft.id}
                className="bg-gray-50 border border-gray-200 rounded-xl p-5 space-y-3 text-xs"
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 border-b border-gray-200 pb-3">
                  <div>
                    <span className="text-gray-500 text-[11px]">To: {draft.recipientEmail}</span>
                    <h3 className="font-bold text-gray-900 text-sm mt-0.5">{draft.subject}</h3>
                  </div>
                  <span className="badge-success">
                    {draft.status}
                  </span>
                </div>

                <div className="bg-white p-4 rounded-lg border border-gray-200 text-gray-900 whitespace-pre-wrap leading-relaxed font-mono text-[11px]">
                  {draft.body}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}