import React from 'react';
import { prisma } from '@/lib/db';
import { Mail, ExternalLink, Send, CheckCircle2 } from 'lucide-react';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function FollowUpsPage() {
  const followUps = await prisma.followUp.findMany({
    orderBy: { createdAt: 'desc' },
    include: { lead: true },
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-dark-card border border-dark-border p-6 rounded-xl">
        <div>
          <h1 className="text-xl font-bold text-dark-bright tracking-tight flex items-center gap-2">
            <Mail className="w-5 h-5 text-brand-purple" /> Automated Follow-up Draft Manager
          </h1>
          <p className="text-xs text-dark-muted mt-1">
            Personalized email responses generated by AI and dispatched via Mailpit SMTP.
          </p>
        </div>

        <a
          href="http://localhost:8025"
          target="_blank"
          rel="noreferrer"
          className="px-3 py-1.5 bg-dark-hover border border-dark-border hover:border-brand-cyan text-dark-bright text-xs font-mono rounded-lg transition flex items-center gap-1.5"
        >
          Open Mailpit Inbox (8025) <ExternalLink className="w-3.5 h-3.5 text-brand-cyan" />
        </a>
      </div>

      <div className="bg-dark-card border border-dark-border rounded-xl p-6 space-y-4">
        {followUps.length === 0 ? (
          <div className="text-center p-8 text-dark-muted text-xs">
            No follow-up drafts generated yet. Submit a qualified lead to trigger automated generation.
          </div>
        ) : (
          <div className="space-y-4">
            {followUps.map((draft) => (
              <div
                key={draft.id}
                className="bg-dark-bg/60 border border-dark-border rounded-xl p-5 space-y-3 text-xs"
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 border-b border-dark-border pb-3">
                  <div>
                    <span className="text-dark-muted text-[11px]">To: {draft.recipientEmail}</span>
                    <h3 className="font-bold text-dark-bright text-sm mt-0.5">{draft.subject}</h3>
                  </div>
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-brand-emerald/10 text-brand-emerald border border-brand-emerald/30">
                    {draft.status}
                  </span>
                </div>

                <div className="bg-dark-card p-4 rounded-lg border border-dark-border text-dark-text whitespace-pre-wrap leading-relaxed font-mono text-[11px]">
                  {draft.body}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
