$bytes = [System.IO.File]::ReadAllBytes("C:\Users\laptopzone\Desktop\LeadPilot AI\app\intelligence\page.tsx")
$content = [System.Text.Encoding]::UTF8.GetString($bytes)
$content = $content -replace '\u2014', '--'  # em dash
$content = $content -replace '\u2013', '-'   # en dash
$content = $content -replace '\u2018', "'"   # left single quote
$content = $content -replace '\u2019', "'"   # right single quote
$content = $content -replace '\u201C', '"'   # left double quote
$content = $content -replace '\u201D', '"'   # right double quote
$content = $content -replace '\u2026', '...' # ellipsis
$content = $content -replace '\u2022', '*'   # bullet
$content = $content -replace '\u201E', '"'   # double low-9 quote
$content = $content -replace '\u201A', ','   # single low-9 quote
$content = $content -replace '\u2039', '<'   # single left angle quote
$content = $content -replace '\u203A', '>'   # single right angle quote
$content = $content -replace '\u00A0', ' '   # non-breaking space
$content = $content -replace '\u2010', '-'   # hyphen
$content = $content -replace '\u2011', '-'   # non-breaking hyphen
$content = $content -replace '\u2012', '-'   # figure dash
$content = $content -replace '\u2212', '-'   # minus sign
$content = $content -replace '\u221E', 'infinity'
$content = $content -replace '\u00D7', 'x'   # multiplication sign
$content = $content -replace '\u2192', '->'  # right arrow
$content = $content -replace '\u2190', '<-'  # left arrow
$content = $content -replace '\u2191', '^'   # up arrow
$content = $content -replace '\u2193', 'v'   # down arrow
$content = $content -replace '\u2264', '<='  # less than or equal
$content = $content -replace '\u2265', '>='  # greater than or equal
$content = $content -replace '\u2260', '!='  # not equal
$content = $content -replace '\u221A', 'sqrt' # square root
$content = $content -replace '\u00B1', '+/-' # plus-minus
$content = $content -replace '\u00B0', 'deg'  # degree
$content = $content -replace '\u00AE', '(R)'  # registered
$content = $content -replace '\u00A9', '(c)'  # copyright
$content = $content -replace '\u2122', '(TM)' # trademark
$content = $content -replace '\u20AC', 'EUR' # euro sign
$content = $content -replace '\u00A3', 'GBP' # pound sign
$content = $content -replace '\u00A5', 'JPY'  # yen sign
$content = $content -replace '\u2020', '†'   # dagger
$content = $content -replace '\u2021', '‡'   # double dagger
$content = $content -replace '\u2030', '‰'   # per mille
$content = $content -replace '\u202F', ' '   # narrow no-break space
$content = $content -replace '\u2009', ' '   # thin space
$content = $content -replace '\u200A', ' '   # hair space
$content = $content -replace '\u200B', ''    # zero width space
$content = $content -replace '\uFEFF', ''    # BOM
$content = $content -replace '\u00A7', '§'   # section sign
$content = $content -replace '\u00B6', '¶'   # pilcrow
$content = $content -replace '\u221E', 'infinity'
$content = $content -replace '\u2015', '---' # horizontal bar
$content = $content -replace '\u2016', '||'  # double vertical line
$content = $content -replace '\u2017', '__'  # double low line
$content = $content -replace '\u203B', '※'   # reference mark
$content = $content -replace '\u203C', '!!'  # double exclamation
$content = $content -replace '\u203D', '?'   # interrobang
$content = $content -replace '\u2047', '??'  # double question
$content = $content -replace '\u2048', '?!'   # question exclamation
$content = $content -replace '\u2049', '!?'   # exclamation question
$content = $content -replace '\u2057', '⁗'   # quad punctuation
$content = $content -replace '\u203E', '‾'   # overline
$content = $content -replace '\u203F', '⁀'   # undertie
$content = $content -replace '\u2040', '⁁'   # character tie
$content = $content -replace '\u2041', '⁂'   # asterism
$content = $content -replace '\u2042', '⁃'   # hyphen bullet
$content = $content -replace '\u2043', '⁄'   # hyphen bullet
$content = $content -replace '\u2044', '/'   # fraction slash
$content = $content -replace '\u2045', '['   # left square bracket
$content = $content -replace '\u2046', ']'   # right square bracket
$content = $content -replace '\u204E', '*'   # low asterisk
$content = $content -replace '\u204F', '⁏'   # reversed semicolon
$content = $content -replace '\u2050', '⁐'   # close up
$content = $content -replace '\u2051', '⁑'   # two asterisks
$content = $content -replace '\u2052', '⁒'   # three asterisks
$content = $content -replace '\u2053', '⁓'   # swung dash
$content = $content -replace '\u2054', '⁔'   # inverted undertie
$content = $content -replace '\u2055', '⁕'   # flower punctuation
$content = $content -replace '\u2056', '⁖'   # three dot punctuation
$content = $content -replace '\u2058', '⁘'   # quadruple prime
$content = $content -replace '\u2059', '⁙'   # five dot punctuation
$content = $content -replace '\u205A', '⁚'   # two dot punctuation
$content = $content -replace '\u205B', '⁛'   # four dot punctuation
$content = $content -replace '\u205C', '⁜'   # three dot punctuation
$content = $content -replace '\u205D', '⁝'   # tricolon
$content = $content -replace '\u205E', '⁞'   # four dot punctuation
$content = $content -replace '\u2060', ''    # word joiner
$content = $content -replace '\u2061', ''    # function application
$content = $content -replace '\u2062', ''    # invisible times
$content = $content -replace '\u2063', ''    # invisible separator
$content = $content -replace '\u2066', ''    # left-to-right isolate
$content = $content -replace '\u2067', ''    # right-to-left isolate
$content = $content -replace '\u2068', ''    # first strong isolate
$content = $content -replace '\u2069', ''    # pop directional isolate
$content = $content -replace '\u206A', ''    # inhibit symmetric swapping
$content = $content -replace '\u206B', ''    # activate symmetric swapping
$content = $content -replace '\u206C', ''    # inhibit arabic form shaping
$content = $content -replace '\u206D', ''    # activate arabic form shaping
$content = $content -replace '\u206E', ''    # national digit shapes
$content = $content -replace '\u206F', ''    # nominal digit shapes
$content = $content -replace '\uFEFF', ''    # BOM
$content = $content -replace '\uFFFE', ''    # BOM (reversed)
$content = $content -replace '\uFFFF', ''    # BOM (reversed)
[System.IO.File]::WriteAllBytes("C:\Users\laptopzone\Desktop\LeadPilot AI\app\intelligence\page.tsx", [System.Text.Encoding]::UTF8.GetBytes($content))
Write-Host "Cleaned non-ASCII characters from intelligence page"

$bytes2 = [System.IO.File]::ReadAllBytes("C:\Users\laptopzone\Desktop\LeadPilot AI\app\submit\page.tsx")
$content2 = [System.Text.Encoding]::UTF8.GetString($bytes2)
$content2 = $content2 -replace '\u2014', '--'
$content2 = $content2 -replace '\u2013', '-'
$content2 = $content2 -replace '\u2018', "'"
$content2 = $content2 -replace '\u2019', "'"
$content2 = $content2 -replace '\u201C', '"'
$content2 = $content2 -replace '\u201D', '"'
$content2 = $content2 -replace '\u2026', '...'
$content2 = $content2 -replace '\u2022', '*'
$content2 = $content2 -replace '\u201E', '"'
$content2 = $content2 -replace '\u201A', ','
$content2 = $content2 -replace '\u2039', '<'
$content2 = $content2 -replace '\u203A', '>'
$content2 = $content2 -replace '\u00A0', ' '
$content2 = $content2 -replace '\u2010', '-'
$content2 = $content2 -replace '\u2011', '-'
$content2 = $content2 -replace '\u2012', '-'
$content2 = $content2 -replace '\u2212', '-'
$content2 = $content2 -replace '\u20AC', 'EUR'
$content2 = $content2 -replace '\u00A3', 'GBP'
$content2 = $content2 -replace '\u00A5', 'JPY'
$content2 = $content2 -replace '\u00AE', '(R)'
$content2 = $content2 -replace '\u00A9', '(c)'
$content2 = $content2 -replace '\u2122', '(TM)'
$content2 = $content2 -replace '\u00A7', '§'
$content2 = $content2 -replace '\u00B6', '¶'
$content2 = $content2 -replace '\u20AC', 'EUR'
$content2 = $content2 -replace '\u00A7', '§'
$content2 = $content2 -replace '\u00B6', '¶'
$content2 = $content2 -replace '\u20AC', 'EUR'
$content2 = $content2 -replace '\u00A7', '§'
$content2 = $content2 -replace '\u00B6', '¶'
$content2 = $content2 -replace '\u20AC', 'EUR'
$content2 = $content2 -replace '\u00A7', '§'
$content2 = $content2 -replace '\u00B6', '¶'
$content2 = $content2 -replace '\u20AC', 'EUR'
$content2 = $content2 -replace '\uFEFF', ''
$content2 = $content2 -replace '\uFFFE', ''
$content2 = $content2 -replace '\uFFFF', ''
[System.IO.File]::WriteAllBytes("C:\Users\laptopzone\Desktop\LeadPilot AI\app\submit\page.tsx", [System.Text.Encoding]::UTF8.GetBytes($content2))
Write-Host "Cleaned non-ASCII characters from submit page"